name: Prepare Docker
description: Checks if Docker is installed and starts the Docker service if necessary.

runs:
  using: "composite"
  steps:
    # Step 1: Check Docker Installation
    - name: Check Docker Installation
      shell: pwsh
      run: |
        try {
          $dockerVersion = docker --version
          if (-Not $dockerVersion) {
            Write-Host "Docker is not installed!"
            exit 1
          } else {
            Write-Host "Docker is installed: $dockerVersion"
          }
        } catch {
          Write-Host "Docker command not found. Please install Docker."
          exit 1
        }

    # Step 2: Start Docker Service
    - name: Start Docker Service
      shell: pwsh
      run: |
        try {
          Start-Service docker
          Write-Host "Docker service started successfully."
        } catch {
          Write-Host "Failed to start Docker service. Please ensure Docker is installed and configured properly."
          exit 1
        }